### ISSUE TITLE
Could not connect to Twilio: Signaling connection disconnected

### ISSUE THREAD

**Issue by muhammadsr** [philnash/screen-capture#4]
Disconnects from the room the second I try to connect. 

```
2019-06-10 21:02:28.647Z | INFO in [connect #1]: Error while connecting to a Room: TwilioError: Signaling connection disconnected
    at SignalingConnectionDisconnectedError.TwilioError (http://localhost:3000/index.js:29565:23)
    at new SignalingConnectionDisconnectedError (http://localhost:3000/index.js:28692:157)
    at InviteClientContext.disconnect (http://localhost:3000/index.js:24755:25)
    at Object.onceWrapper (http://localhost:3000/index.js:30785:30)
    at emitOne (http://localhost:3000/index.js:30602:13)
    at InviteClientContext.emit (http://localhost:3000/index.js:30680:7)
    at InviteClientContext.sendRequest (http://localhost:3000/index.js:4831:10)
    at InviteClientContext.acceptAndTerminate (http://localhost:3000/index.js:5261:12)
    at onFailure (http://localhost:3000/index.js:6652:23)
```

**Comment by philnash** [comment]
This might sound like a silly question, but are you connected to the internet when you try this?

Also, have you filled in all the environment variables in `.env` listed [in the readme here](https://github.com/philnash/screen-capture#video-chat-example)? If so, can you check your access token that you generate at https://jwt.io/. A video access token should have a video grant added to it and you should be able to verify the token with your Twilio Auth Token.

Have you changed anything in the code or were you just trying to run it as is?

Let me know how you get on with those checks.

**Comment by muhammadsr** [comment]
- I am connected to the internet.
- I checked the access token that was generated by the video chat tool. I found it in the console under `X-Twilio-AccessToken`. Not sure if this was the one you were referring to. 
![Screen Shot 2019-06-11 at 10 35 25 AM](https://user-images.githubusercontent.com/1937488/59294211-baffea80-8c35-11e9-9d96-d9133257f8fe.png)
- I did not change anything in the code.

**Comment by philnash** [comment]
Ah, ok. The application itself actually generates codes that look a bit like this, but they should work if you haven't changed anything.

One more thing, are you using the production credentials or test credentials? Video chat will not work with test credentials.

**Comment by muhammadsr** [comment]
I am using the `ACCOUNT SID` from the live credentials. I also generated the API Keys from https://www.twilio.com/console/video/runtime/api-keys.

**Comment by tolufakiyesi** [comment]
Upgrading the twilio version fixed this for me as mentioned here


[https://github.com/twilio/twilio-video.js/issues/576#issuecomment-473775024](https://github.com/twilio/twilio-video.js/issues/576#issuecomment-473775024)
